# Site settings
title: 100haiku
email: donkapetra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A haiku every day for 100 days.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://haiku.petradonka.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Global settings
timezone: Europe/Zurich

# Build settings
markdown: kramdown
host: 0.0.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      font-size: "100"